### ISSUE TITLE
Cannot read property 'childNodes' of undefined at getExpandElement

### ISSUE THREAD

**Issue by Almenit** [wnr/element-resize-detector#61]
Async access on unmounted element. Se stacktrace.
![capture](https://cloud.githubusercontent.com/assets/5937466/19230611/c6aba898-8ed5-11e6-91d0-67b4cb6c9c7f.PNG)

**Comment by wnr** [comment]
Interesting, thanks for the report. This should have been fixed with the latest version, are you using 1.1.9?

**Comment by Almenit** [comment]
Yes we do. Double checked it this time :-)

**Comment by wnr** [comment]
Haha thanks! :) I'll look into it.

**Comment by wnr** [comment]
Hi again, I've investigated this issue further. My theory is that your component removes the injected elements, without calling `uninstall` before. Could this be the case?

**Comment by Almenit** [comment]
No really don't think so. We use React and we uninstall it in our componentWillUnmount

**Comment by Almenit** [comment]
I don't know if this helps? But this is the state of the element when it fails
getState(element) returns =>
Object
busy: true id: 1 listeners: Array[0] startSize: Object __proto__: Object

**Comment by wnr** [comment]
Hmm okay. I'm still pretty confident that the injected elements somehow gets removed (or that the element listened to is moved), because I cannot figure out how else this error would occur. If you could create a reduced example showing the error, it would help a lot!

**Comment by Almenit** [comment]
I think this has to do with a timing issue. If I debug it I can see that my element is uninstalled ok. But I reuse the same element and my guess is that that element have a pending event. At the start of installation you register new state on the element, but It still don't have a container, at that point the event (the setTimeout) kicks in and the exception occurs. If I add a check that the state must have a container then it works ok. I hope this can help you.

**Comment by wnr** [comment]
Sorry for the late response, I've been on vacation. Yes, that actually makes sense. I'll try reproduce it that way, thanks :)

**Comment by wnr** [comment]
It seems like I managed to reproduce this issue in a test case, see https://github.com/wnr/element-resize-detector/blob/WIP-1.1.11/test/element-resize-detector_test.js#L847

**Comment by wnr** [comment]
I have merged a fix for this in branch WIP-1.1.11. Could you perhaps see if this version solves your issues? https://github.com/wnr/element-resize-detector/blob/WIP-1.1.11/dist/element-resize-detector.js

**Comment by wnr** [comment]
This has now been published as 1.1.11.

**Comment by benkaiser** [comment]
I think I'm still seeing this issue on this line:

![image](https://user-images.githubusercontent.com/608054/33799860-a3e87e32-dce8-11e7-9718-81888fa120a7.png)

I'll submit a PR to address the issue.
